//$Header: /as2/de/mendelson/comm/as2/preferences/PreferencesPanelLog.java 20    17/03/26 9:24 Heller $
package de.mendelson.comm.as2.preferences;

import de.mendelson.util.MecResourceBundle;
import de.mendelson.util.MendelsonMultiResolutionImage;
import de.mendelson.util.balloontip.BalloonToolTip;
import de.mendelson.util.clientserver.BaseClient;
import de.mendelson.util.clientserver.clients.preferences.PreferencesClient;
import de.mendelson.util.uinotification.UINotification;
import java.util.MissingResourceException;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/*
 * Copyright (C) mendelson-e-commerce GmbH Berlin Germany
 *
 * This software is subject to the license agreement set forth in the license.
 * Please read and agree to all terms before using this software.
 * Other product and brand names are trademarks of their respective owners.
 */
/**
 * Panel to define special log events
 *
 * @author S.Heller
 * @version: $Revision: 20 $
 */
public final class PreferencesPanelLog extends PreferencesPanel {

    private static final MendelsonMultiResolutionImage IMAGE_LOG
            = MendelsonMultiResolutionImage.fromSVG("/de/mendelson/comm/as2/preferences/log.svg",
                    JDialogPreferences.IMAGE_HEIGHT);

    private static final MecResourceBundle rb;

    static {
        try {
            rb = (MecResourceBundle) ResourceBundle.getBundle(
                    ResourceBundlePreferences.class.getName());
        } catch (MissingResourceException e) {
            throw new RuntimeException("Oops..resource bundle "
                    + e.getClassName() + " not found.");
        }
    }

    private final PreferencesClient preferences;
    private String preferencesStrAtLoadTime = "";

    /**
     * Creates new form PreferencesPanelDirectories
     */
    public PreferencesPanelLog(BaseClient baseClient) {
        this.preferences = new PreferencesClient(baseClient);
        this.initComponents();
    }

    /**
     * Sets new preferences to this panel to changes/modify
     */
    @Override
    public void loadPreferences() {
        this.switchLogAutoMessageDelete.setSelected(this.preferences.getBoolean(PreferencesAS2.AUTO_MSG_DELETE_LOG));
        this.switchLogMessageProcessing.setSelected(this.preferences.getBoolean(PreferencesAS2.EXTENDED_LOG_PROCESSING));
        this.switchHTTPRequestLog.setSelected(this.preferences.getBoolean(PreferencesAS2.EMBEDDED_HTTP_SERVER_REQUESTLOG));
        this.switchLogPollProcess.setSelected(this.preferences.getBoolean(PreferencesAS2.LOG_POLL_PROCESS));
        this.preferencesStrAtLoadTime = this.captureSettingsToStr();
    }

    /**
     * Helper method to find out if there are changes in the GUI before storing
     * them to the server
     */
    private String captureSettingsToStr() {
        StringBuilder builder = new StringBuilder();
        builder.append(PreferencesAS2.AUTO_MSG_DELETE_LOG).append("=")
                .append(this.switchLogAutoMessageDelete.isSelected()).append(";");
        builder.append(PreferencesAS2.LOG_POLL_PROCESS).append("=")
                .append(this.switchLogPollProcess.isSelected()).append(";");
        builder.append(PreferencesAS2.EMBEDDED_HTTP_SERVER_REQUESTLOG).append("=")
                .append(this.switchHTTPRequestLog.isSelected()).append(";");
        builder.append(PreferencesAS2.EXTENDED_LOG_PROCESSING).append("=")
                .append(this.switchLogMessageProcessing.isSelected()).append(";");
        return (builder.toString());
    }

    @Override
    public boolean preferencesAreModified() {
        return (!this.preferencesStrAtLoadTime.equals(this.captureSettingsToStr()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelMargin = new javax.swing.JPanel();
        jPanelSpace = new javax.swing.JPanel();
        switchLogAutoMessageDelete = new de.mendelson.util.toggleswitch.ToggleSwitch();
        switchHTTPRequestLog = new de.mendelson.util.toggleswitch.ToggleSwitch();
        switchLogPollProcess = new de.mendelson.util.toggleswitch.ToggleSwitch();
        jPanelSpace559 = new javax.swing.JPanel();
        jPanelUIHelpLabelLogHTTPRequests = new de.mendelson.util.balloontip.JPanelUIHelpLabel();
        jPanelSpace7743 = new javax.swing.JPanel();
        jPanelUIHelpLabelLogPollProcess = new de.mendelson.util.balloontip.JPanelUIHelpLabel();
        jPanelUIHelpLabelLogAutoMessageDelete = new de.mendelson.util.balloontip.JPanelUIHelpLabel();
        jPanelUIHelpLabelLogMessageProcessing = new de.mendelson.util.balloontip.JPanelUIHelpLabel();
        switchLogMessageProcessing = new de.mendelson.util.toggleswitch.ToggleSwitch();

        setLayout(new java.awt.GridBagLayout());

        jPanelMargin.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanelMargin.add(jPanelSpace, gridBagConstraints);

        switchLogAutoMessageDelete.setDisplayStatusText(true);
        switchLogAutoMessageDelete.setHorizontalTextPosition(SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelMargin.add(switchLogAutoMessageDelete, gridBagConstraints);

        switchHTTPRequestLog.setDisplayStatusText(true);
        switchHTTPRequestLog.setHorizontalTextPosition(SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelMargin.add(switchHTTPRequestLog, gridBagConstraints);

        switchLogPollProcess.setDisplayStatusText(true);
        switchLogPollProcess.setHorizontalTextPosition(SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelMargin.add(switchLogPollProcess, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelMargin.add(jPanelSpace559, gridBagConstraints);

        jPanelUIHelpLabelLogHTTPRequests.setToolTipText(this.rb.getResourceString( "label.loghttprequests.help" ));
        jPanelUIHelpLabelLogHTTPRequests.setText(this.rb.getResourceString( "label.loghttprequests" ));
        jPanelUIHelpLabelLogHTTPRequests.setTriangleAlignment(BalloonToolTip.TRIANGLE_ALIGNMENT_CENTER
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelMargin.add(jPanelUIHelpLabelLogHTTPRequests, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 5, 5);
        jPanelMargin.add(jPanelSpace7743, gridBagConstraints);

        jPanelUIHelpLabelLogPollProcess.setToolTipText(this.rb.getResourceString( "label.logpollprocess.help" ));
        jPanelUIHelpLabelLogPollProcess.setText(this.rb.getResourceString( "label.logpollprocess" ));
        jPanelUIHelpLabelLogPollProcess.setTriangleAlignment(BalloonToolTip.TRIANGLE_ALIGNMENT_TOP
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelMargin.add(jPanelUIHelpLabelLogPollProcess, gridBagConstraints);

        jPanelUIHelpLabelLogAutoMessageDelete.setToolTipText(this.rb.getResourceString( "label.deletemsglog.help"));
        jPanelUIHelpLabelLogAutoMessageDelete.setText(this.rb.getResourceString( "label.deletemsglog"));
        jPanelUIHelpLabelLogAutoMessageDelete.setTriangleAlignment(BalloonToolTip.TRIANGLE_ALIGNMENT_TOP
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelMargin.add(jPanelUIHelpLabelLogAutoMessageDelete, gridBagConstraints);

        jPanelUIHelpLabelLogMessageProcessing.setToolTipText(this.rb.getResourceString( "label.logmessageprocessing.help"));
        jPanelUIHelpLabelLogMessageProcessing.setText(this.rb.getResourceString( "label.logmessageprocessing"));
        jPanelUIHelpLabelLogMessageProcessing.setTriangleAlignment(BalloonToolTip.TRIANGLE_ALIGNMENT_TOP
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelMargin.add(jPanelUIHelpLabelLogMessageProcessing, gridBagConstraints);

        switchLogMessageProcessing.setDisplayStatusText(true);
        switchLogMessageProcessing.setHorizontalTextPosition(SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelMargin.add(switchLogMessageProcessing, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jPanelMargin, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelMargin;
    private javax.swing.JPanel jPanelSpace;
    private javax.swing.JPanel jPanelSpace559;
    private javax.swing.JPanel jPanelSpace7743;
    private de.mendelson.util.balloontip.JPanelUIHelpLabel jPanelUIHelpLabelLogAutoMessageDelete;
    private de.mendelson.util.balloontip.JPanelUIHelpLabel jPanelUIHelpLabelLogHTTPRequests;
    private de.mendelson.util.balloontip.JPanelUIHelpLabel jPanelUIHelpLabelLogMessageProcessing;
    private de.mendelson.util.balloontip.JPanelUIHelpLabel jPanelUIHelpLabelLogPollProcess;
    private de.mendelson.util.toggleswitch.ToggleSwitch switchHTTPRequestLog;
    private de.mendelson.util.toggleswitch.ToggleSwitch switchLogAutoMessageDelete;
    private de.mendelson.util.toggleswitch.ToggleSwitch switchLogMessageProcessing;
    private de.mendelson.util.toggleswitch.ToggleSwitch switchLogPollProcess;
    // End of variables declaration//GEN-END:variables

    @Override
    public void savePreferences() {
        try {
            this.preferences.putBoolean(PreferencesAS2.LOG_POLL_PROCESS, this.switchLogPollProcess.isSelected());
            this.preferences.putBoolean(PreferencesAS2.AUTO_MSG_DELETE_LOG, this.switchLogAutoMessageDelete.isSelected());
            this.preferences.putBoolean(PreferencesAS2.EMBEDDED_HTTP_SERVER_REQUESTLOG,
                    this.switchHTTPRequestLog.isSelected());
            this.preferences.putBoolean(PreferencesAS2.EXTENDED_LOG_PROCESSING,
                    this.switchLogMessageProcessing.isSelected());
        } catch (Throwable e) {
            UINotification.instance().addNotification(e);
        }
    }

    @Override
    public ImageIcon getIcon() {
        return (new ImageIcon(IMAGE_LOG));

    }

    @Override
    public String getTabResource() {
        return ("tab.log");
    }

}
