#
# Update script db version 51 to db version 52
# Generate a table for the montly throughput of the system
# $Author: heller $
# $Revision: 1.2 $
#
#Throughput
#
CREATE TABLE throughput(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,month CHAR(6) NOT NULL,transactioncounter BIGINT NOT NULL);
CREATE INDEX idx_throughput_month ON throughput(month);

