#
# Update script db version 47 to db version 48
# All the oauth accounts and create possible reference in the notification
# $Author: heller $
# $Revision: 1.2 $
#
#
CREATE TABLE oauth2(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,authendpoint VARCHAR(1024)NOT NULL,authscope VARCHAR(1024)NOT NULL,tokenendpoint VARCHAR(1024)NOT NULL,clientsecret VARCHAR(1024)NOT NULL,clientid VARCHAR(1024)NOT NULL,authcode VARCHAR(8192),accesstoken VARCHAR(8192),refreshtoken VARCHAR(8192),accesstokenuntil BIGINT DEFAULT 0 NOT NULL,username VARCHAR(256));
ALTER TABLE notification ADD COLUMN usesmtpoauth2 INTEGER DEFAULT 0 NOT NULL
ALTER TABLE notification ADD COLUMN smtpoauth2id INTEGER
ALTER TABLE notification ADD FOREIGN KEY(smtpoauth2id)REFERENCES oauth2(id)

